apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-example01
  labels:
    app: web01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web01
  template:
    metadata:
      name: deploy-example01
      labels:
        app: web01
    spec:
      containers:
      - name: nginx
        image: nginx