apiVersion: v1
kind: Pod
metadata:
  name: initcontainer-example01
  labels:
    app: initcontainer-example01
spec:
  volumes:
  - name: vol01
    emptyDir: {}
  initContainers:
  - name: busybox
    image: busybox
    volumeMounts:
    - name: vol01
      mountPath: /data
    command: ["sh","-c","echo Example of using init containers > /data/index.html"]
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: vol01
      mountPath: /usr/share/nginx/html