apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod01
  name: pod01
spec:
  containers:
  - image: nginx
    name: pod01
  nodeSelector:
    kubernetes.io/hostname: control3
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Exists
