apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc01
  labels:
    type: pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/foo
    type: DirectoryOrCreate