apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cGFzc3cwcmQ=
kind: Secret
metadata:
  name: mariadb-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb
    envFrom:
    - secretRef:
        name: mariadb-secret
      