apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: madhu-sc
  labels:
    type: storageclass
provisioner: k8s.io/minikube-hostpath
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate