apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir-example01
  labels:
    app: volume-emptydir-example01
spec:
  volumes:
  - name: vol01
    emptyDir: {}
  initContainers:
  - name: busybox
    image: busybox
    volumeMounts:
    - name: vol01
      mountPath: /data
    command: ["sh","-c","echo hello world > /data/index.html"]
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: vol01
      mountPath: /usr/share/nginx/html