apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb1
  name: myweb1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb1
  template:
    metadata:
      labels:
        app: myweb1
        type: canary
    spec:
      containers:
      - image: nginx:1.14
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb2
  name: myweb2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myweb2
  template:
    metadata:
      labels:
        app: myweb2
        type: canary
    spec:
      containers:
      - image: nginx:latest
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: canary
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  type: NodePort
  selector:
    type: canary
