apiVersion: v1
kind: Namespace
metadata:
  name: ckad-ns3
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar-pod
  name: sidecar-pod
  namespace: ckad-ns3
spec:
  volumes:
  - name: vol01
    hostPath:
      path: /tmp/task4-vol
      type: DirectoryOrCreate
  containers:
  - command: ["sh","-c","while true; do date >> /var/log/date.log; sleep 5; done"]
    image: busybox
    name: busybox
    volumeMounts:
    - name: vol01
      mountPath: /var/log
    resources: {}
  - name: nginx
    image: nginx
    volumeMounts:
    - name: vol01
      mountPath: /usr/share/nginx/html
    imagePullPolicy: IfNotPresent
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}