apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sleepybox
  name: sleepybox
spec:
  securityContext:
    fsGroup: 2000
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox:latest
    name: sleepybox
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}