apiVersion: v1
kind: Namespace
metadata:
  name: ckad-1311
spec: {}
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1311-pv
  namespace: ckad-1311
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/ckad-1311-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 1311-pvc
  namespace: ckad-1311
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: 1311-pod
  name: 1311-pod
  namespace: ckad-1311
spec:
  volumes:
  - name: vol01
    persistentVolumeClaim:
      claimName: 1311-pvc
  containers:
  - image: nginx
    name: 1311-pod
    resources: {}
    volumeMounts:
    - name: vol01
      mountPath: /webdata
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}