apiVersion: v1
kind: Namespace
metadata:
  name: limited
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: limited-quota
  namespace: limited
spec:
  hard:
    cpu: "1"
    memory: 2Gi
    pods: "5"
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restrictnginx
  name: restrictnginx
  namespace: limited
spec:
  replicas: 3
  selector:
    matchLabels:
      app: restrictnginx
  strategy: {}
  template:
    metadata:
      labels:
        app: restrictnginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
          limits:
            memory: 256Mi  
            cpu: 200m
status: {}