apiVersion: v1
kind: Namespace
metadata:
  name: ckad-ns1
spec: {}
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-a
  name: pod-a
  namespace : ckad-ns1
spec:
  containers:
  - image: httpd
    name: pod-a
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-b
  name: pod-b
  namespace : ckad-ns1
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: alpine
    name: pod-b
    resources: {}
  - name: nginx
    image: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}