apiVersion: v1
data:
  password: c2VjcmV0
kind: Secret
metadata:
  name: task2secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: secretapp
  name: secretapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secretapp
  strategy: {}
  template:
    metadata:
      labels:
        app: secretapp
    spec:
      containers:
      - image: nginx
        name: nginx
        envFrom:
        - secretRef:
            name: task2secret
        resources: {}
status: {}