apiVersion: v1
kind: Namespace
metadata:
  name: ckad-ns6
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: ckad-ns6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  strategy: {}
  template:
    metadata:

      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx:1.19
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: ckad-ns6
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  selector:
    app: nginx-deployment
  type: NodePort
status:
  loadBalancer: {}