apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: restricted
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: access
spec: {}
status: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nwpolicy01
  namespace: restricted
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - access
    ports:
    - port: 80
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: restrictedpod
  name: restrictedpod
  namespace: restricted
spec:
  containers:
  - image: nginx
    name: restrictedpod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: accesspod
  name: accesspod
  namespace: access
spec:
  containers:
  - args:
    - sleep
    - "3600"
    image: busybox
    name: accesspod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: restrictedpod
  name: restrictedpod
  namespace: restricted
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: restrictedpod
status:
  loadBalancer: {}