apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: limited
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: limitedquota
  namespace: limited
spec:
  hard:
    memory: 2Gi
    pods: "5"
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab128deploy
  name: lab128deploy
  namespace: limited
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab128deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab128deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}