apiVersion: v1
kind: Namespace
metadata:
  name: access
spec: {}
status: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lab1211
  namespace: access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lab1211-role
  namespace: access
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lab1211-rolebinding
  namespace: access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lab1211-role
subjects:
- kind: ServiceAccount
  name: lab1211
  namespace: access