apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab126deploy
  name: lab126deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lab126deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab126deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lab126deploy
  name: lab126deploy
spec:
  ports:
  - port: 32567
    protocol: TCP
    targetPort: 32567
  selector:
    app: lab126deploy
  type: NodePort
status:
  loadBalancer: {}